name: kidney-pseudospace
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy<2
  - pandas
  - pyarrow
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - anndata
  - scanpy
  - python-igraph
  - leidenalg
  - statsmodels
  - patsy
  - h5py
  - numba
  - r-base
  - r-harmony=2.0.5
  - rpy2
  - jupyterlab
  - nbformat
  - pytest
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - shapely>=2
      - gseapy>=1.3,<1.4
      - genes2genes @ git+https://github.com/Teichlab/Genes2Genes.git@42ba945d370a864464a2d3cc7174aa0ee451e600
